name: os build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt install nasm -y
    - name: make
      run: make
    - name: os release
      uses: actions/upload-artifact@v3.1.0
      with:
        name: os
        path: build/os.bin
